DEPO_KABULLER_2026 = [
    {'hammadde': 'Patates Unu', 'tedarikci': 'Satütaş', 'tedarikci_lot_no': '251212', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': None, 'skt_tett': None, 'miktar_kg': 436.8, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': '2026 geçmiş veri aktarımı. Lot numarası REDBOX master operasyon Excel lot kayıtlarından alınmıştır.', 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Nişasta', 'tedarikci': 'Değirmenci Gıda', 'tedarikci_lot_no': '0058138875', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': '09.09.2025', 'skt_tett': '09.09.2027', 'miktar_kg': 215.04, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': "2026 geçmiş veri aktarımı. Kabul tarihi üretim öncesi stok yenileme bilgisine göre oluşturulmuştur. Miktar, kayıtlı 2026 üretimlerinin reçete tüketim karşılığı olarak oluşturulmuştur. Dönem sonu fiziksel hammadde stoku 0 kg'dır.", 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Mısır Unu', 'tedarikci': 'Sizin Gıda', 'tedarikci_lot_no': '9226', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': '20.02.2026', 'skt_tett': '20.02.2027', 'miktar_kg': 107.52, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': "2026 geçmiş veri aktarımı. Kabul tarihi üretim öncesi stok yenileme bilgisine göre oluşturulmuştur. Miktar, kayıtlı 2026 üretimlerinin reçete tüketim karşılığı olarak oluşturulmuştur. Dönem sonu fiziksel hammadde stoku 0 kg'dır.", 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Tavuk Çeşnisi', 'tedarikci': 'Ankara Gıda', 'tedarikci_lot_no': '01.09.EY', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': None, 'skt_tett': None, 'miktar_kg': 26.88, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': '2026 geçmiş veri aktarımı. Lot numarası REDBOX master operasyon Excel lot kayıtlarından alınmıştır.', 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Sarımsak Tozu', 'tedarikci': 'Sizin Gıda', 'tedarikci_lot_no': '170226-157', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': '17.02.2026', 'skt_tett': '17.02.2028', 'miktar_kg': 5.376, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': "2026 geçmiş veri aktarımı. Kabul tarihi üretim öncesi stok yenileme bilgisine göre oluşturulmuştur. Miktar, kayıtlı 2026 üretimlerinin reçete tüketim karşılığı olarak oluşturulmuştur. Dönem sonu fiziksel hammadde stoku 0 kg'dır.", 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Karabiber', 'tedarikci': 'Metro Market', 'tedarikci_lot_no': '070426-693', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': '07.04.2026', 'skt_tett': '07.04.2028', 'miktar_kg': 2.016, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': "2026 geçmiş veri aktarımı. Kabul tarihi üretim öncesi stok yenileme bilgisine göre oluşturulmuştur. Miktar, kayıtlı 2026 üretimlerinin reçete tüketim karşılığı olarak oluşturulmuştur. Dönem sonu fiziksel hammadde stoku 0 kg'dır.", 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Tuz', 'tedarikci': 'Sizin Gıda', 'tedarikci_lot_no': '20425', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': '23.07.2025', 'skt_tett': '23.07.2026', 'miktar_kg': 12.096, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': "2026 geçmiş veri aktarımı. Kabul tarihi üretim öncesi stok yenileme bilgisine göre oluşturulmuştur. Miktar, kayıtlı 2026 üretimlerinin reçete tüketim karşılığı olarak oluşturulmuştur. Dönem sonu fiziksel hammadde stoku 0 kg'dır.", 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
    {'hammadde': 'Metilselüloz Benecel A4M E461', 'tedarikci': 'IMCD Türkiye', 'tedarikci_lot_no': '2743063', 'kabul_tarihi': '14.04.2026', 'uretim_tarihi': '08.01.2026', 'skt_tett': '08.01.2028', 'miktar_kg': 10.08, 'tarih_kaynagi': 'TAHMINI_URETIM_ONCESI', 'aciklama': "2026 geçmiş veri aktarımı. Kabul tarihi üretim öncesi stok yenileme bilgisine göre oluşturulmuştur. Miktar, kayıtlı 2026 üretimlerinin reçete tüketim karşılığı olarak oluşturulmuştur. Dönem sonu fiziksel hammadde stoku 0 kg'dır.", 'miktar_kaynagi': '2026_URETIM_RECETE_TUKETIM_KARSILIGI'},
]
